export const animAll = `duration-200 transition-all ease-default`;
export const animColor = `duration-300 transition-color ease-default`;
export const interaction = `betterhover:hover:bg-neutral-700/50`;
export const interactionInput = `has-[:focus]:ring-2 has-[:focus]:ring-neutral-500 has-[:focus]:ring-inset betterhover:hover:bg-neutral-700 has-[:focus]:bg-neutral-800`;
export const button = `p-1 ${animAll} ${interaction} stroke-white cursor-pointer rounded-md active:scale-90`;
export const buttonSelection = `p-0.5 ${animAll} ${interaction} stroke-white cursor-pointer rounded-md`;
export const buttonHoverOnly = `p-1 ${animAll} stroke-white rounded-md ${interaction}`;
export const buttonBorder = `border-2 border-neutral-800`
export const buttonAlt = `bg-neutral-400 text-neutral-950 betterhover:hover:bg-neutral-400/50 `
export const morphOn = `bg-neutral-900`;
export const iconHide = `scale-90 opacity-0 pointer-events-none invisible`;
export const iconShow = `scale-100 opacity-100 delay-100 visible`;
export const selected = `bg-neutral-800/50`;
export const buttonSwap = `flex h-full w-full absolute top-0 left-0`;
